# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_addroot.ipynb.

# %% auto 0
__all__ = ['project_root_path', 'foo']

# %% ../nbs/00_addroot.ipynb 4
import os, sys
from pathlib import Path

project_root_path = None

# %% ../nbs/00_addroot.ipynb 9
def foo(): pass
